version: "3.9"

networks:
  mirror:
    driver: bridge

services:

  proxy:
    container_name: proxy
    image: nginx
    environment:
      API_KEY: ${IMDB_API_KEY}
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/env.template:/etc/nginx/templates/env.conf.template:ro
      - ./ssl/cert.pem:/etc/ssl/cert.pem:ro
      - ./ssl/key.pem:/etc/ssl/key.pem:ro
    networks:
      - mirror
    ports:
      # - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    restart: unless-stopped

  api:
    container_name: api
    build: ./api
    networks:
      - mirror
    restart: unless-stopped

  webtorrent:
    container_name: webtorrent
    build: ./webtorrent
    networks:
      - mirror
    restart: unless-stopped
